# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Memorable Places' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Firebase/Core'
  pod ‘Google-Mobile-Ads-SDK’

  # Pods for Memorable Places

  target 'Memorable PlacesTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Memorable PlacesUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
